version: '3.7'

services:
  db:
    image: postgres
    ports:
      - "5500:5432"
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - ./data:/var/lib/postgresql/data
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6400:6379'
    command: "redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"